### ISSUE TITLE
err0r

### ISSUE THREAD

**Issue by Anonamusri** [TheSpeedX/TBomb#13]
Traceback (most recent call last):
  File "bomber.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec')) 		
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'zlib'

**Comment by TheSpeedX** [comment]
https://askubuntu.com/questions/741609/install-python-package-locally

This might solve your issue...

**Comment by kitarou404** [comment]
File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 2, in <module>            File "<string>", line 509, in <module>        ValueError: invalid literal for int() with base 10: 'Ash Ash Ash'

**Comment by kitarou404** [comment]
How to overcome it?

File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 8, in <module>            File "<string>", line 2, in <module>            File "<string>", line 509, in <module>        ValueError: invalid literal for int() with base 10: 'Ash Ash Ash'

**Comment by TheSpeedX** [comment]
Input Numbers Not Text

Its asking to input Number of messages not what is the message
