### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Vitanil** [TheSpeedX/TBomb#14]
After sending 3-6 sms error appears

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 509, in <module>
  File "<string>", line 285, in start
  File "<string>", line 194, in getapi
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

I used the time delay: 30 sec
My country code: +7

**Comment by nfsnfs007** [comment]
Same happened to me!

**Comment by user6996** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 525, in <module>
  File "<string>", line 73, in logit
  File "<string>", line 338, in checkin
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from Noniam using indian code

**Comment by ragewire** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 578, in <module>
  File "<string>", line 73, in logit
  File "<string>", line 338, in checkin
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PREFIX'

**Comment by TheSpeedX** [comment]
@ragewire and @user6996 see this is solved at #9 
So closing issue

**Comment by TheSpeedX** [comment]
@Vitanil Sorry but the apis in TBomb Are Out dated 

But We are currently working on its apk version so we might or might not solve it
