### ISSUE TITLE
kali linux

### ISSUE THREAD

**Issue by tempyman** [TheSpeedX/TBomb#3]
Please Wait While We Verify TBomb...

	Verification Successfull !!!
Do You Want To Bomb Indian Number (Y/N): N
	Enter Your Country Code (Without +) 969
	Enter Target Number: +969 **********
Enter Number of Messages: hello
Traceback (most recent call last):
  File "bomber.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec')) 		
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 227, in <module>
ValueError: invalid literal for int() with base 10: 'hello'
root@kali:~/Tools Hacking/TBomb# 

4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

**Comment by TheSpeedX** [comment]
Its Written Number Of Messages Not Whats The Message

Number of messages must be like 10 , 20 ,30...

Custom SMS Are Not Supported Yet...

**Comment by legendzki** [comment]
its always say check your connentions pls tell me how to slove it
