### ISSUE TITLE
it give error please tell me how to fix i am python3.9 and also install pip

### ISSUE THREAD

**Issue by Vikas5686** [TheSpeedX/TBomb#314]
Downloading Latest Files...
Traceback (most recent call last):
  File "/home/kali/Downloads/TBomb/bomber.py", line 19, in <module>
    from utils.decorators import MessageDecorator
  File "/home/kali/Downloads/TBomb/utils/decorators.py", line 1, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'
 RUN TBomb Again...
Press any key to continue...

**Comment by Vikas5686** [comment]
when i install it it give warnings 1 more error

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.                                                                                                
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/certifi/                                                                                                     
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/certifi/                                                                                                     
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/certifi/                                                                                                     
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/certifi/                                                                                                     
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/certifi/

ERROR: Could not find a version that satisfies the requirement certifi>=2020.6.20 (from versions: none)
ERROR: No matching distribution found for certifi>=2020.6.20

**Comment by TheSpeedX** [comment]
Have you tried [PIP Method](https://github.com/TheSpeedX/TBomb#install-by-pip-recommended)

**Comment by TheSpeedX** [comment]
Hello!

After careful consideration, I’ve decided to close all open issues for this repository. 
This project has grown into something beyond my initial expectations, but I’ve found it increasingly difficult to maintain due to low-quality contributions and spam pull requests/issues. Furthermore, I am transitioning to new ventures, and I won’t be able to continue contributing to TBomb any further.

Though I’m stepping away, I’m grateful to all those who have used and supported this tool. TBomb will remain usable through Git and PyPI, but I won’t be actively involved moving forward.

Thank you for your understanding and for using this tool!
Best regards,
TheSpeedX
