### ISSUE TITLE
What can I do about that?
 
I run the TBomb and it show me that massage:

### ISSUE THREAD

**Issue by TeoTsiok** [TheSpeedX/TBomb#362]
Traceback (most recent call last):                           File "/data/data/com.termux/files/home/TBomb/bomber.py", line 19, in <module>
    from utils.decorators import MessageDecorator            File "/data/data/com.termux/files/home/TBomb/utils/decorators.py", line 1, in <module>                                  from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'

**Comment by shado200** [comment]
help me for this I can complet him

**Comment by 0n1cOn3** [comment]
Give a shot:

```pip3 install colorama```

Then try again.

**Comment by TheSpeedX** [comment]
Hello!

After careful consideration, I’ve decided to close all open issues for this repository. 
This project has grown into something beyond my initial expectations, but I’ve found it increasingly difficult to maintain due to low-quality contributions and spam pull requests/issues. Furthermore, I am transitioning to new ventures, and I won’t be able to continue contributing to TBomb any further.

Though I’m stepping away, I’m grateful to all those who have used and supported this tool. TBomb will remain usable through Git and PyPI, but I won’t be actively involved moving forward.

Thank you for your understanding and for using this tool!
Best regards,
TheSpeedX
