### ISSUE TITLE
Checking for updates Problem

### ISSUE THREAD

**Issue by Aamanshaikh21** [TheSpeedX/TBomb#416]
Whenever tried to Start bombing After Choosing a Call or SMS Bombing 
It Stuck At **Checking for updates**

& Waiting for a while it Shows
**_ Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn                     conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection         raise err
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)                                              ConnectionAbortedError: [Errno 103] Software caused connection abort

During handling of the above exception, another exception occurred:

Traceback (most recent call last):                                  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen                   httplib_response = self._make_request(                                               ^^^^^^^^^^^^^^^^^^^                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x715ac22450>: Failed to establish a new connection: [Errno 103] Software caused connection abort

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TheSpeedX/TBomb/master/.version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x715ac22450>: Failed to establish a new connection: [Errno 103] Software caused connection abort'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TBomb/./bomber.py", line 448, in <module>
    selectnode(mode=avail_choice[choice].lower())
  File "/data/data/com.termux/files/home/TBomb/./bomber.py", line 310, in selectnode
    check_for_updates()
  File "/data/data/com.termux/files/home/TBomb/./bomber.py", line 175, in check_for_updates
    fver = requests.get(
           ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TheSpeedX/TBomb/master/.version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x715ac22450>: Failed to establish a new connection: [Errno 103] Software caused connection abort'))_**

After Changing Domains From nano bomber.py still it Stuck At **Checking for please** help me

**Comment by 0n1cOn3** [comment]
Ehmm... Python 3.11... Downgrade to 3.9 and your good to go🥲.

**Comment by Arkaaap** [comment]
@0n1cOn3 give the command line in order to downgrade python version on termux

**Comment by 0n1cOn3** [comment]
> @0n1cOn3 give the command line in order to downgrade python version on termux

Google exists :)

**Comment by AdMediastic** [comment]
It is simply impossible to downgrade the python version, easier said than done! 
Especially in Parrot OS! 

I am getting the same error! 
Will somebody from the TBomb team please fix this!

**Comment by TheSpeedX** [comment]
Hello!

After careful consideration, I’ve decided to close all open issues for this repository. 
This project has grown into something beyond my initial expectations, but I’ve found it increasingly difficult to maintain due to low-quality contributions and spam pull requests/issues. Furthermore, I am transitioning to new ventures, and I won’t be able to continue contributing to TBomb any further.

Though I’m stepping away, I’m grateful to all those who have used and supported this tool. TBomb will remain usable through Git and PyPI, but I won’t be actively involved moving forward.

Thank you for your understanding and for using this tool!
Best regards,
TheSpeedX
