### ISSUE TITLE
traceback KeyError:'PREFIX

### ISSUE THREAD

**Issue by thunderram** [TheSpeedX/TBomb#9]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 578, in <module>
  File "<string>", line 73, in logit
  File "<string>", line 338, in checkin
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PREFIX'

**Comment by WickedG0d** [comment]
Same Error!!

**Comment by Kart1k5** [comment]
me too getting this error using kali linux

**Comment by TheSpeedX** [comment]
This Tool Was Tested On Ubuntu And it worked Fine

Please type the following to solve the issue

export PREFIX=/tmp

**Comment by amrithmmh** [comment]
> This Tool Was Tested On Ubuntu And it worked Fine
> 
> Please type the following to solve the issue
> 
> export PREFIX=/tmp

also run the bash script without sudo

**Comment by ZaidTed** [comment]
where to type this = export PREFIX=/tmp

**Comment by amrithmmh** [comment]
export PREFIX=/tmp should be typed in the terminal you are using in Ubuntu then execute the Tbomb script without sudo or with sudo try both one should work . It worked for me fine in Ubuntu

**Comment by ZaidTed** [comment]
Thanks TheSpeedX/TBomb

**Comment by madkos9k** [comment]
File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 490, in <module>
  File "<string>", line 124, in wgOpn
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by madkos9k** [comment]
File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 509, in <module>
ValueError: invalid literal for int() with base 10: ''

**Comment by madkos9k** [comment]
File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 8, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 544, in <module>
  File "<string>", line 313, in wgOpF
  File "<string>", line 133, in wgOpK
ValueError: '38' is not in list

**Comment by TheSpeedX** [comment]
Make Sure To Type Correct Country Code

Check Your Country Code in Google once...
